server:
  port: 0

spring:
  application:
    name: sender-service

telegram:
  bot:
    token: 6725676716:AAFq-CZT5GU7V-C0XCMfQRXospDwYmJa7gM

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
