server:
  port: 1100

spring:
  application:
    name: sender-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

telegram:
  bot:
    token: 6725676716:AAFq-CZT5GU7V-C0XCMfQRXospDwYmJa7gM