server:
  port: 9000

spring:
  application:
    name: file-service

springdoc:
  api-docs:
    path: /file-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka