spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ens_db
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka