spring:
  application:
    name: security-service
  datasource:
    username: root
    password: root
    url: jdbc:h2:mem:jwt_security
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2

token:
  signing:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970