spring:
  application:
    name: message-template-service
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    driverClassName: org.postgresql.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka